### 사용자는 회원가입 할 수 있다.

POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "password": "your_password",
  "name": "your_name",
  "email": "your_email@example.com",
  "nickName": "your_nickname",
  "role": "STUDENT"
}




### 사용자는 로그인 후 JWT 토큰을 받을 수 있다.

POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
  "email": "your_email@example.com",
  "password": "your_password"
}

### 로그인후 사용자는 인가가 필요한 페이지를 접근할수 있다.

GET http://localhost:8080/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ5b3VyX2VtYWlsQGV4YW1wbGUuY29tIiwiYXV0aCI6IlNUVURFTlQiLCJpYXQiOjE2ODg4MTk5NjMsImV4cCI6MTY4ODkwNTM2M30.zly2cwFOlXCHKSFtb06K4S0uLu6GW3NlqUqt_MC3qSUDtbj-1-F9ISS7-elDYct3cjGLCR2J2fwoZo5d_pGPQQ

### ACCESSTOKEN 만료 요청

POST http://localhost:8080/api/auth/refresh
Content-Type: application/json

{
  "refresh_token": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ5b3VyX2VtYWlsQGV4YW1wbGUuY29tIiwiYXV0aCI6IlNUVURFTlQiLCJpYXQiOjE2ODg4MTU2MDMsImV4cCI6MTY4OTQyMDQwM30.tX7vRZj-PasUggoc0xUheYx_CunBMzI1bUZzFQBet2z4OZ8UV_ESYO9FLql0uVOOoTwrrjs7t8iUFd285oShFg"
}
